// GENERATED by tools/gen_rom_map.py from tools/ms1_romdata.py.
// Do not edit by hand -- re-run the generator.
//
// Byte base and byte size of every SDRAM region, per game mode.
// A region a mode does not have is given base 0 and size 0; the
// core must never fetch from it (mode D has no sound 68000, no
// third scroll layer and no second OKI).

// ---- mode B: 3031040 bytes (2.89 MB), sets: avspirit, monkelf, edf, edfa, edfb, edfu, hayaosi1
localparam [23:0] MAIN_BASE_B = 24'h000000;  localparam [24:0] MAIN_SIZE_B = 25'h0080000;
localparam [23:0] SND_BASE_B = 24'h080000;  localparam [24:0] SND_SIZE_B = 25'h0040000;
localparam [23:0] MCU_BASE_B = 24'h0C0000;  localparam [24:0] MCU_SIZE_B = 25'h0004000;
localparam [23:0] L0_BASE_B = 24'h0C4000;  localparam [24:0] L0_SIZE_B = 25'h0080000;
localparam [23:0] L1_BASE_B = 24'h144000;  localparam [24:0] L1_SIZE_B = 25'h0080000;
localparam [23:0] L2_BASE_B = 24'h1C4000;  localparam [24:0] L2_SIZE_B = 25'h0020000;
localparam [23:0] SPR_BASE_B = 24'h1E4000;  localparam [24:0] SPR_SIZE_B = 25'h0080000;
localparam [23:0] OKI1_BASE_B = 24'h264000;  localparam [24:0] OKI1_SIZE_B = 25'h0040000;
localparam [23:0] OKI2_BASE_B = 24'h2A4000;  localparam [24:0] OKI2_SIZE_B = 25'h0040000;
localparam [24:0] TOTAL_B = 25'h02E4000;

// ---- mode C: 3424256 bytes (3.27 MB), sets: 64street, 64streetj, 64streetja, bigstrik, chimerab, chimeraba, cybattlr
localparam [23:0] MAIN_BASE_C = 24'h000000;  localparam [24:0] MAIN_SIZE_C = 25'h0080000;
localparam [23:0] SND_BASE_C = 24'h080000;  localparam [24:0] SND_SIZE_C = 25'h0020000;
localparam [23:0] MCU_BASE_C = 24'h0A0000;  localparam [24:0] MCU_SIZE_C = 25'h0004000;
localparam [23:0] L0_BASE_C = 24'h0A4000;  localparam [24:0] L0_SIZE_C = 25'h0080000;
localparam [23:0] L1_BASE_C = 24'h124000;  localparam [24:0] L1_SIZE_C = 25'h0080000;
localparam [23:0] L2_BASE_C = 24'h1A4000;  localparam [24:0] L2_SIZE_C = 25'h0020000;
localparam [23:0] SPR_BASE_C = 24'h1C4000;  localparam [24:0] SPR_SIZE_C = 25'h0100000;
localparam [23:0] OKI1_BASE_C = 24'h2C4000;  localparam [24:0] OKI1_SIZE_C = 25'h0040000;
localparam [23:0] OKI2_BASE_C = 24'h304000;  localparam [24:0] OKI2_SIZE_C = 25'h0040000;
localparam [24:0] TOTAL_C = 25'h0344000;

// ---- mode D: 2899968 bytes (2.77 MB), sets: peekaboo, peekaboou
localparam [23:0] MAIN_BASE_D = 24'h000000;  localparam [24:0] MAIN_SIZE_D = 25'h0040000;
localparam [23:0] SND_BASE_D = 24'h000000;  localparam [24:0] SND_SIZE_D = 25'h0000000;
localparam [23:0] MCU_BASE_D = 24'h040000;  localparam [24:0] MCU_SIZE_D = 25'h0004000;
localparam [23:0] L0_BASE_D = 24'h044000;  localparam [24:0] L0_SIZE_D = 25'h0080000;
localparam [23:0] L1_BASE_D = 24'h0C4000;  localparam [24:0] L1_SIZE_D = 25'h0080000;
localparam [23:0] L2_BASE_D = 24'h000000;  localparam [24:0] L2_SIZE_D = 25'h0000000;
localparam [23:0] SPR_BASE_D = 24'h144000;  localparam [24:0] SPR_SIZE_D = 25'h0080000;
localparam [23:0] OKI1_BASE_D = 24'h1C4000;  localparam [24:0] OKI1_SIZE_D = 25'h0100000;
localparam [23:0] OKI2_BASE_D = 24'h000000;  localparam [24:0] OKI2_SIZE_D = 25'h0000000;
localparam [24:0] TOTAL_D = 25'h02C4000;

// Selected by the core's `mode` input (0 = B, 1 = C, 2 = D).
wire [23:0] MAIN_BASE = (mode == 2'd0) ? MAIN_BASE_B : (mode == 2'd1) ? MAIN_BASE_C : MAIN_BASE_D;
wire [23:0] SND_BASE = (mode == 2'd0) ? SND_BASE_B : (mode == 2'd1) ? SND_BASE_C : SND_BASE_D;
wire [23:0] MCU_BASE = (mode == 2'd0) ? MCU_BASE_B : (mode == 2'd1) ? MCU_BASE_C : MCU_BASE_D;
wire [23:0] L0_BASE = (mode == 2'd0) ? L0_BASE_B : (mode == 2'd1) ? L0_BASE_C : L0_BASE_D;
wire [23:0] L1_BASE = (mode == 2'd0) ? L1_BASE_B : (mode == 2'd1) ? L1_BASE_C : L1_BASE_D;
wire [23:0] L2_BASE = (mode == 2'd0) ? L2_BASE_B : (mode == 2'd1) ? L2_BASE_C : L2_BASE_D;
wire [23:0] SPR_BASE = (mode == 2'd0) ? SPR_BASE_B : (mode == 2'd1) ? SPR_BASE_C : SPR_BASE_D;
wire [23:0] OKI1_BASE = (mode == 2'd0) ? OKI1_BASE_B : (mode == 2'd1) ? OKI1_BASE_C : OKI1_BASE_D;
wire [23:0] OKI2_BASE = (mode == 2'd0) ? OKI2_BASE_B : (mode == 2'd1) ? OKI2_BASE_C : OKI2_BASE_D;

